name: ci

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings[python]
      - run: mkdocs gh-deploy --force
